### ISSUE TITLE
Add a simple way to add escape clause

### ISSUE THREAD

**Issue by chengenzhao** [vert-x3/vertx-sql-common#27]
### Version
- vert.x sql common: 3.3.0 
### Context

http://stackoverflow.com/questions/8247970/using-like-wildcard-in-prepared-statement

Hi there:

For current version, if there are some special characters like % _ [ in the queryParams/jsonArray then the query will fail and the solution is to use like wildcard as stated in the above link, so I would suggest to use like wildcard in prepared statement automatically in the queryWithParams func/api rather than users implement by themselves. 

Thanks

**Comment by pmlopes** [comment]
This is not a good idea since it is not portable and might interfere with the statement itself, for example in postgres you can have a query like this:

``` sql
select * from xxx where x ~ 'aa*b{3}%c+' order by 1;
```

This is a totally valid query since you can do regular expressions as params the percent char there is not a escape.

Also in postgres you can escape with the `%` char and not `!` like to the SO question:

``` sql
select * from xxx where x like 'aaabbb%%ccc' order by 1;
```
