### ISSUE TITLE
The batchUpdate doesn't work asynchronously

### ISSUE THREAD

**Issue by brainzest** [vert-x3/vertx-sql-common#30]
### Version
- vert.x core:3.3.0
- vert.x sql common:3.3.0
  *vertx-mysql-postgresql-client 3.3.0
### Context

I encountered an exception which looks suspicious while  doing Batch operations  http://vertx.io/docs/vertx-sql-common/java/#_batch_operations
Please see the issue defined here:
 http://stackoverflow.com/questions/38295740/run-multiple-sql-queries-asynchronously-in-vertx-vert-x-3

**Comment by pmlopes** [comment]
There are several things here:
1. the async driver does not support batching so you can workaround it by concatenating the sql in a big statement and issue it once.
2. In your example you have a while loop relying on an async update of the stop condition, which means since the update is not blocking your while loop will be running "forever" until there is a forced thread switch from the JVM and therefore a warning of blocking the event loop.
