### ISSUE TITLE
Cannot pass binary data to SQLConnection.updateWithParams

### ISSUE THREAD

**Issue by mhstnsc** [vert-x3/vertx-sql-common#32]
### Version
- vert.x core: 3.3.3
- vert.x sql common: 3.3.3
### Context

I am trying to perform an SQL query to insert data to a BINARY(16) column however the API takes a JsonArray as parameter however i get an error that my data is too long.

I set the parameters with the following code:

```
byte[] uuid = new byte[16];
secureRandom.nextBytes(uuid);
JsonArray params = new JsonArray().add(uuid);
```

However the JsonArray.add converts the parameters to base64 (obviously longer) and the code to prepare the sql statement does not care about the type and just gets everything as String thus the base64 encoding.

**Comment by pmlopes** [comment]
That is correct, JSON does not know binary as a type to when you add a binary to a JSON document you'll get it automatically converted to Base64, however this can be handled at the database side, e.g.:

``` sql
insert into table (FROM_BASE64(?))
```

where `FROM_BASE64` is a MySQL function: http://dev.mysql.com/doc/refman/5.6/en/string-functions.html#function_from-base64 same can be done for Postgres: `decode('YmFzZTY0IGVuY29kZWQgc3RyaW5n', 'base64')` and also for MSSQL, Oracle etc...

**Comment by mhstnsc** [comment]
Sure it works, but it is a hack.

I see no reason why the API cannot handle this. Statement API (at least in java) allows very well for this. Why not just expose that one since this is just iterating over Json array and calls that API. 

I get my data from binary sources like protobuf messages. Why should it be converted to base64 and then just convert it back to binary form.

**Comment by pmlopes** [comment]
I cannot say that it is a hack. The JSON spec does not support binary data, so you're already limited at that point and the sql-common interface is by no means a JDBC frontend. The idea is to allow other non JDBC clients to connect to databases such as the async mysql postgres client which does not follow the java.sql.\* semantics.

If your concern is to avoid encode/decode you can still avoid it. For example on mysql in the docs you can read:

> The BINARY and VARBINARY types are similar to CHAR and VARCHAR, except that they contain binary strings rather than nonbinary strings. 

So you can have something like:

```
mysql> CREATE TABLE t (c BINARY(3));
Query OK, 0 rows affected (0.01 sec)

mysql> INSERT INTO t SET c = 'a';
Query OK, 1 row affected (0.01 sec)
```

Which means that given the right character encoding you can use a plain string from your bytes to insert data and it would work fine on the sql-common interface:

``` java
byte[] uuid = new byte[16];
secureRandom.nextBytes(uuid);
JsonArray params = new JsonArray().add(new String(uuid, StandardCharsets.ISO_8859_1);
```

This will just wrap your bytes, no transformation will happen, and you can insert it in your `BINARY` field.

**Comment by mhstnsc** [comment]
> The JSON spec does not support binary data

You do not have to use json. This is the choice of the API and IMO is limiting. SQL has more data types. Squashing them all into String does not sound like very SQL conforming. Sure Json can still be an option but why not just convert from Json to another representation which is more powerful but also expose the more type-safe API

> For example on mysql in the docs you can read:

Since this API is generic as you suggested there should not be a discussion about specific cases IMO. 

The generic question that should be asked is what does SQL standard say about data types.

**Comment by pmlopes** [comment]
The choice of JSON is not related in any kind to SQL, it is the common pattern in the whole Vert.x ecosystem. JSON is supported by virtually any programming language, making it a good candidate for the polyglot aspect of the framework. JSON is also the lingua franca of internet services (as of the time of writing of this message) so it makes sense to use what all developers understand that use some other (probably more powerful) but less common format.

SQL is an older language and indeed it has a much more diverse type system, however SQL has been designed as a query language that will be interpreted/handled by the remote DBMS. In order to do this the SQL language is not compiled on the programming language your application is written but almost all the time passed as a string of text to the DBMS to be evaluated and processed.

Given this, vert.x still gives you the full power of SQL, with the method `execute(String sql, ...)` you can virtually use any SQL supported type even the types JDBC does not support out of the box, think of JSONB from Postgres for example, or say that you're doing some computations using complex numbers (which for example you can do on Postgres) and you need to calculate the complex conjugate of a column. There would not be a direct mapping for that column type.

So to answer your question:

> The generic question that should be asked is what does SQL standard say about data types.

It doesn't matter if you really need complex data types that the limited JSON type system does not support, you can always do it in SQL and execute it with the common clients.

**Comment by pmlopes** [comment]
Since this has become more of a discussion on the decisions done while designing the API rather than the subject, I'll close the issue and recommend to keep discussing this in the forum: https://groups.google.com/forum/#!forum/vertx where the whole community can participate and give their input, rather than an one-to-one discussion.
