### ISSUE TITLE
Support return/output params and resultsets with stored procedures

### ISSUE THREAD

**Issue by purplefox** [vert-x3/vertx-sql-common#5]
See https://groups.google.com/forum/?fromgroups#!searchin/vertx/stored$20procedure/vertx/Z61Zly1Oanc/urB3pQZ9eaEJ

and https://groups.google.com/forum/?fromgroups#!topic/vertx/-ZofvUfbzj8

**Comment by pmlopes** [comment]
This will require some refactoring:
- add a new method to run callable statements
- specify a JSON of inputs
- specify a JSON of output

and since we are doing this, probably we could also work the way query params are handled. Currently we use `?` and array index, however for callable statements we needs to know which index is for input and which is for output. I'd propose to use a different notation e.g.:

```
select * from table where id = :id and name <> :somename
```

This was we can refer to properties on a json to get the id and somename. This does not sound like a big win but for callable statements:

```
{call some_function(:a, :b, :c)}
```

we can now have 2 jsons like:

```
in = {a: 1}
out = {b:"string", c:"number"}
```

we can now know which args are `in` and which ones are `out`. We can also know which type to encode the output ones since we the name of the json type.
